version: "3"

services:
  api:
    build: .
    container_name: deepseek-api
    restart: always
    ports:
      - "8812:8812"
    environment:
      - PORT=8812
      - DEEPSEEK_API_KEY=""
      - DEEPSEEK_API_URL=https://api.deepseek.com
      - ALLOWED_ORIGINS=https://oooo.blog,https://chenpeel.github.io
    volumes:
      - ./logs:/app/logs
