version: "3"
services:
  api:
    build: .
    container_name: deepseek-api
    restart: always
    ports:
      - "8812:8812"
    environment:
      - PORT=8812
      - NODE_ENV=production
      - USE_HTTPS=false  
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=https://api.deepseek.com
      - ALLOWED_ORIGINS=https://oooo.blog,https://chenpeel.github.io
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
    networks:
      - frontend
      - backend
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: chat-redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - backend

networks:
  frontend:
  backend:
    internal: true

volumes:
  redis-data: