version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - /home/Gamma/.acme.sh/chenpeel.xyz:/etc/ssl/live/chenpeel.xyz:ro
    networks:
      - frontend
    depends_on:
      - api

  api:
    build: .
    container_name: deepseek-api
    restart: always
    expose:
      - "8812"
    environment:
      - PORT=8812
      - USE_HTTPS=false
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=https://api.deepseek.com
      - ALLOWED_ORIGINS=https://oooo.blog,https://chenpeel.github.io
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - LOG_DIR=/app/logs/server
    volumes:
      - ./logs:/app/logs
    networks:
      - frontend
      - backend
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: chat-redis
    restart: always
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --logfile /var/log/redis/redis.log
    volumes:
      - redis-data:/data
      - ./logs/redis:/var/log/redis
    networks:
      - backend

networks:
  frontend:
  backend:
    internal: true

volumes:
  redis-data:
